const LOCATION_CHANGE = '@@router/LOCATION_CHANGE';
const FETCH_LICENSES_STARTED = 'REPOS/FETCH_LICENSES_STARTED';
const FETCH_LICENSES_SUCCEEDED = 'REPOS/FETCH_LICENSES_SUCCEEDED';
const FETCH_LICENSES_FAILED = 'REPOS/FETCH_LICENSES_FAILED';
const FETCH_REPOS_STARTED = 'REPOS/FETCH_REPOS_STARTED';
const FETCH_REPOS_SUCCEEDED = 'REPOS/FETCH_REPOS_SUCCEEDED';
const FETCH_REPOS_FAILURE = 'REPOS/FETCH_REPOS_FAILURE';
const SET_QUERY = 'REPOS/SET_QUERY';

export {
  LOCATION_CHANGE,
  FETCH_LICENSES_STARTED,
  FETCH_LICENSES_SUCCEEDED,
  FETCH_LICENSES_FAILED,
  FETCH_REPOS_STARTED,
  FETCH_REPOS_SUCCEEDED,
  FETCH_REPOS_FAILURE,
  SET_QUERY,
};
