const LOCATION_CHANGE = '@@router/LOCATION_CHANGE';
const FETCH_LICENSES_STARTED = 'REPOS/FETCH_LICENSES_STARTED';
const FETCH_LICENSES_SUCCEEDED = 'REPOS/FETCH_LICENSES_SUCCEEDED';
const FETCH_LICENSES_FAILED = 'REPOS/FETCH_LICENSES_FAILED';
const FETCH_REPOS_STARTED = 'REPOS/FETCH_REPOS_STARTED';
const FETCH_REPOS_SUCCEEDED = 'REPOS/FETCH_REPOS_SUCCEEDED';
const FETCH_REPOS_FAILURE = 'REPOS/FETCH_REPOS_FAILURE';
const SET_NAME = 'REPOS/SET_NAME';
const SET_LANG = 'REPOS/SET_LANG';
const SET_LICENSE = 'REPOS/SET_SET_LICENSE';
const SET_PAGE = 'REPOS/SET_PAGE';

const setLang = language => ({
  type: SET_LANG,
  language
});

const setLicense = license => ({
  type: SET_LICENSE,
  license
});

const setPage = page => ({
  type: SET_PAGE,
  page
});

export {
  LOCATION_CHANGE,
  FETCH_LICENSES_STARTED,
  FETCH_LICENSES_SUCCEEDED,
  FETCH_LICENSES_FAILED,
  FETCH_REPOS_STARTED,
  FETCH_REPOS_SUCCEEDED,
  FETCH_REPOS_FAILURE,
  SET_NAME,
  SET_LANG,
  SET_LICENSE,
  SET_PAGE,
  setLang,
  setLicense,
  setPage
};
